# name: Comment on PR

# on:
#   pull_request:
#     types: [opened, synchronize]

# jobs:
#   comment:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Check if this is the first time the PR is opened
#         run: |
#           if [ "$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits | jq '. | length')" -eq "1" ]; then
#             echo "::set-output name=first_open::true"
#           else
#             echo "::set-output name=first_open::false"
#           fi
#         id: check_first_open

#       - name: Comment on PR
#         uses: actions/github-script@v4
#         with:
#           script: |
#             const firstOpen = ${{ steps.check_first_open.outputs.first_open }};
#             const body = firstOpen ? 'Hello World! and opened' : 'updated';
#             github.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: body
#             })
#           ad: first_open
